#默认的品质
default_rarity: common

#自动输出所有内置的附魔
auto_release: true

#若您为附魔主菜单设置了back按钮，这是玩家点击按钮时执行的指令
main_menu_back: sl

#数据库内容
database:
  host: localhost
  port: 3306
  user: minecraft
  password: password
  database: minecraft

#若有更新内容，在op上线时提醒
update_msg: true

#对玩家背包内的非法物品的进行检测，并修改它们
anti_illegal_item:
  enable: false #是否打开此功能，会略微增加性能消耗
  interval: 60 #检测的tick
  check_list:
    - MAX_CAPABILITY
    - CONFLICT_GROUP
    - CONFLICT_ENCHANT