# 默认使用 TabooLib 语言文本解析
# 若此项配置为 true, 则对语言文本解析 MiniMessage, 且不允许出现原版颜色符号
# 默认为 false
use_mini_message: false

#默认的品质
default_rarity: common

#自动输出所有内置的附魔
auto_release: true

#若您为附魔主菜单设置了back按钮，这是玩家点击按钮时执行的指令
main_menu_back: sl

#数据库内容
database:
  host: localhost
  port: 3306
  user: minecraft
  password: password
  database: minecraft