name: SplendidEnchants
main: hamsteryds.splendidenchants.enchants.SplendidEnchants
version: 0.0.1
load: STARTUP
description: "SplendidEnchants 附魔扩展插件"
authors:
  - 白熊
  - xiaozhangup

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.21